version: "3.2"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: dibaunaumh/bldg-server:v074
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
      - "4443:4443"
    env_file: docker.env
    depends_on:
      db:
          condition: service_healthy
    # command:
    #   - ./run.sh